'''
Add categories JSON column to products table.
'''

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'add_categories_to_products'
down_revision = "001_init"  # set to previous revision hash if known, otherwise leave None for manual ordering
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    # PostgreSQL supports IF NOT EXISTS; SQLite fallback inside try/except.
    if conn.dialect.name == "postgresql":
        conn.execute(sa.text("ALTER TABLE products ADD COLUMN IF NOT EXISTS categories JSON DEFAULT '[]'::jsonb"))
    else:
        try:
            op.add_column('products', sa.Column('categories', sa.JSON(), nullable=True, server_default='[]'))
        except Exception:
            pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'categories')
    # ### end Alembic commands ###
