'''
Add categories JSON column to products table.
'''

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'add_categories_to_products'
down_revision = None  # set to previous revision hash if known, otherwise leave None for manual ordering
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('categories', sa.JSON(), nullable=True, server_default='[]'))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'categories')
    # ### end Alembic commands ###
